// <auto-generated />
namespace _8020SummativePRG522.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SA : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SA));
        
        string IMigrationMetadata.Id
        {
            get { return "202109151044540_SA"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
